spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.sql.init.mode=always
spring.jpa.hibernate.ddl-auto=none
spring.mvc.format.date-time=yyyy-MM-dd HH:mm:ss
stats-server.url=http://stats-server:9090
logbook.format.style=http
logging.level.org.zalando.logbook=TRACE
logbook.format.default-body-size=1000
logbook.json.write.headers.exclude=Authorization,X-Sharer-User-Id,Cookie
logbook.exclude=/actuator/**,/health
logbook.write.max-body-size=5000


